theme = "gruvbox-dark"

[icons]
name = "awesome5"
[icons.overrides]
net_wired = " ﯱ"
net_up = "⇡"
net_down = "⇣"
memory_mem = "  "
memory_swap = "  "
bat_full = "  "
bat_charging = "  "
bat_discharging = "  "
bat = "  "
time = " "

[[block]]
block = "net"
device = "ens33"
ip = true
speed_min_unit = "B"
hide_missing = true
hide_inactive = true

[[block]]
block = "load"

[[block]]
block = "disk_space"
alias = ""
info_type = "used"
unit = "Percent"
show_percentage = true
warning = 80
alert = 90

[[block]]
block = "memory"
display_type = "memory"
clickable = false
format_mem = "{MAg}"

[[block]]
block = "memory"
display_type = "swap"
clickable = false
format_swap = "{SUm}"

[[block]]
block = "battery"
device = "BAT1"
format = "{percentage}%"
good = 90
info = 63
warning = 38
critical = 10

[[block]]
block = "time"
format = "%l:%M:%S %p"
interval = 1
